/**
 * This class is generated by jOOQ
 */
package jooq;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

import javax.annotation.Generated;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.8.1"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_2729CAED_CA18_4B1C_8A81_1DE083695255</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_2729CAED_CA18_4B1C_8A81_1DE083695255 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_2729CAED_CA18_4B1C_8A81_1DE083695255", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
